### ISSUE TITLE
Download link for MiTeC Windows Registry Recovery is vey slow, hang up installation

### ISSUE THREAD

**Issue by Qynklee** [digitalsleuth/WIN-FOR#6]
```
version: 3.1.2
description: MiTeC Windows Registry Recovery. Registry hive file viewer and analyzer
homepage: https://www.mitec.cz/wrr.html
license: Proprietary
changelog: https://www.mitec.cz/Data/XML/data_wrrvh.xml
url: https://www.mitec.cz/Downloads/WRR.zip
hash: 13b65261ce4e175e8799564d4e0dd699e2a2c6c2af69761e6b374195611a0196
bin: WRR.exe
shortcuts:
- - WRR.exe
  - MiTeC\Windows Registry Recovery
checkver:
  url: https://www.mitec.cz/Data/XML/data_wrrvh.xml
  xpath: /VH/RECORD[DATE!='under development']/VERSION
autoupdate:
  url: https://www.mitec.cz/Downloads/WRR.zip
```
I found this info in other github, installation hang up when install it. I think need config timeout when download and retry after installation completed
![image](https://github.com/digitalsleuth/WIN-FOR/assets/23394219/2e028869-7249-41da-92db-733704eb7d2a)
